name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Verify Go installation
        run: |
          echo "Go version:"
          go version
          echo "Go environment:"
          go env
          which go
          export GOROOT=$(go env GOROOT)
          export PATH=$GOROOT/bin:$PATH

      - name: Install dependencies
        run: |
          export GOROOT=$(go env GOROOT)
          export PATH=$GOROOT/bin:$PATH
          go mod tidy

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: your-app-name:latest

  deploy:
    needs: build  # Зависит от успешной сборки Docker-образа
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
